# config/meta.yml

meta_title: 'EBWiki'
meta_description: 'EBWiki is a webapp working to harness the power of community to end bias in law enforcement that
                    has led to disparate treatment of people of color with tragic results'
meta_image: 'EBWikiLogo.png'
twitter_account: '@endbiaswiki'