name: Docker Image Test

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - local-development-documenation

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        run: make all test stop

